src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java

This is a fix for defect: https://issues.jenkins-ci.org/browse/JENKINS-52338
Due to this issue, the saved value of "AutoUnlink issue" checkbox was not loading while editing a Jenkins job.
Verified by building plugin locally and using local Jenkins.

JENKINS-52338 - added a missing data publisher for AutoUnlink checkbox

---

src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/api/TestToIssueMappingApi.java

This is a fix for defect: https://issues.jenkins-ci.org/browse/JENKINS-52341
Older logic was assuming that if argument job contains character "/" then it is a matrix project. But this was causing conflict when a normal Jenkins job exists under some sub-folder. This fix will check if the parent item to the job is Matrix project then will be processed accordingly. If it is not Matrix project then it will simply get item by full name (to resolve the full Jenkins job path).
Verified by building the plugin locally and on local Jenkins.

JENKINS-52341 - added logic to handle project residing under sub-folder

---

pom.xml
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestAction.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraUtils.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/restclientextensions/FullStatus.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/restclientextensions/JiraRestClientExtension.java

*  Promise has moved to new namespace: io.atlassian.util.concurrent.Promise
*  Bump dependecies for Jenkins and jenkins-ci to run tests

JENKINS-61171: Bump dependency to jira-rest-java-client-core:5.2.1

---

src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestAction.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraUtils.java

- Fixes [JENKINS-56371](https://issues.jenkins.io/browse/JENKINS-56371)
- Also fixes on attach ticket to test result on duplicated entries that are case results
- Before this PR
- After this PR

[JENKINS-56371] Fix on multiple junit publishers

---

src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java

See [JENKINS-56371](https://issues.jenkins.io/browse/JENKINS-56371)
- Previous PR (https://github.com/jenkinsci/JiraTestResultReporter-plugin/pull/23) was not properly working at all. 
- Previous PR was only fixing one corner case, now `TestData` is provided in a proper way
- Tested locally:

[JENKINS-56371] Fix on multiple junit publishers (2nd round)

---

src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestAction.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraUtils.java

- Current code of the plugin relies on `TestObject.getId()` method to setup the mapping between Jira tickets and failed tests
- Main issue here is that when we use this plugin on a multibranch pipeline with some dynamic branching names on its stages then, `autoresolve` capabilities will not work as expected due to some fixed tests could not be resolved, apparently because the fixed tests were executed on a different branch than the original test failure
- Root cause is because the `getId` method setups the branch name as part of the test reference, and this is stored in the `JiraIssueKeyToTestMap.json` file
- Example: 
```
{
"junit/plugins/LdapPluginTest/ATH___ATH_5___login_no_such_user": "JIRA-12456",
"junit/core/PluginManagerTest/ATH___ATH_0___reproduce": "JIRA-12345",
[...]
}
```
- So, …

Bugfix autoresolve test reference on different stage name

---

src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraUtils.java

- Current JQL escape logic is not working based on https://jira.atlassian.com/browse/JRASERVER-25092 and https://jira.atlassian.com/browse/JRASERVER-66244
- Updated escape logic method and provide support for detecting duplicates on parameterized tests

Manage escape JQL based on JRASERVER-25092 and provide support for parameterized tests

---

src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraIssueTrigger.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestAction.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraUtils.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/TestToIssueMapping.java

- JiraTestResultReporter plugin relies on `JiraIssueJobConfigs.json` file to retrieve all the configuration fields to be used in generating Jira tickets on test failures
- If users setup in their Jenkinsfile something like:
```
[...]
def jiraFields = [jiraStringField(fieldKey: 'summary', value: jiraSummaryPrefix + '${TEST_PACKAGE_CLASS_METHOD_NAME}')]
jiraTestResultReporter(configs: jiraFields,
projectKey: jiraProject,
issueType: '3', 
autoRaiseIssue: true,
autoResolveIssue: false,
autoUnlinkIssue: false
)
```
- Where `jiraSummaryPrefix` is something calculated during the execution of the Jenkinsfile, then this value is being overridden every time in the JSON file mentioned above.
- In addition, if the user request to perform a Jira ticket creation through UI (badge) then the global …

Manual creation of Jira issues should use global config only

---

src/test/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataTest.java

Addition of a simple test class for JiraTestData.java.
The project did not have any units from src/test/java so I have decided to get that ball rolling here.
issue: https://github.com/jenkinsci/JiraTestResultReporter-plugin/issues/101

Add test class for JiraTestData.java (2 tests)

---

src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraUtils.java

- Provides support for using `?` char on queries against JIRA to search for duplicates
- Tested with `com.cloudbees.casc.e2e.BundleE2ETest.(?)` provides a valid escaped `com.cloudbees.casc.e2e.BundleE2ETest.(\\?)` which works perfectly fine with JIRA to query

Add ? as supported char for queries against JIRA

---

src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java

- If we use multiple publishers in the `testDataPublisher` sometimes we hit a race condition where the rest of the data provided by other publishers goes away.
- The main reason is that the JiraTestDataPublisher was setting the data instead of adding new data
```[tasklist]
```

Fix race condition on using multiple publishers

---

src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java

- Method `contributeTestData` just should only to provide the test data to be included in the test result
- This method was wrongly adding that data here instead of deferring that to the `junit-plugin`. See https://github.com/jenkinsci/junit-plugin/blob/master/src/main/java/hudson/tasks/junit/JUnitResultArchiver.java#L294
- Tested locally and working as expected
```[tasklist]
```

Test data should be added by the JUnitResultArchiver

---

src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestData.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataRegistry.java

- Use of `parallel` in pipelines with the JiraTestDataResultReporter publisher makes this to provide repeated results on the /testReport due to multiple generations of duplicated JiraTestAction entities
- Then badge.jelly renders all of them for all the parallel branches
- Main reason is the generation of a JiraTestData for each branch execution. Each build should have only one JiraTestData to provide.
- This PR fixes this issue by maintaining in a in-memory registry all the mappings between JiraTestData and build URLs.
- Tested locally
- Before the PR
- After the PR

Fix on parallel branches bug

---

README.md
pom.xml
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestAction.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraUtils.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JobConfigMapping.java
src/main/resources/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher/config.jelly

- Before this PR the attachments added to the Jira tickets are always the stderr, stdout and error stacktrace and details
- After this PR, if the test result has additional attachments provided by third-party tools (like the junit-attachments publisher) these would be also added to the Jira ticket.
- Tested with Jira and Jenkins locally and working as expected
- Jenkins attachment
- Jira attachment (contains the one from the junit-attachment in addition to the current ones - stderr, stdout, etc.)
```[tasklist]
```

Add attachments from the junit-attachments plugin into Jira attachments

---

pom.xml
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JobConfigMapping.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/MetadataCache.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/TestToIssueMapping.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/api/TestToIssueMappingApi.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/config/SelectableArrayFields.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/config/SelectableFields.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/config/StringArrayFields.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/config/StringFields.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/config/UserFields.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/restclientextensions/FullStatus.java

- Fixes https://github.com/jenkinsci/junit-plugin/issues/644

Bump BOM fo fix JUnit issues

---

src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/BearerAuthenticationHandler.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
src/main/resources/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher/global.jelly
src/main/resources/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher/help-useBearerAuth.html

Fixes #140
- added global option for usage of password field for Bearer Token as described in #140, similar to jira plugin
- harmonized whitespace usage within the file and changes tabs to spaces.
Tested with Jenkins https://www.jenkins.io/changelog-stable/#v2.462.2 and none cloud aka enterprise Jira. Change should be backwards compatible and the default behaviour is not to use the bearer token but basic auth as before.

Added bearer token support

---

src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JobConfigMapping.java

Fixes #166. (I hope; untested.) https://github.com/jenkinsci/JiraTestResultReporter-plugin/blob/87b530ef775ac982024d1e0889b6baedfeb165ef/src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JobConfigMapping.java#L47-L49 is a nonstandard pattern and does not seem like a good idea at all.

NPE fix from `JiraTestDataPublisher.getJobName`

---

src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/config/SelectableArrayFields.java

fixes #143 
08:24:17  [WARNING] /home/jenkins/agent/workspace/TestResultReporter-plugin_master/src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/config/SelectableArrayFields.java:[169,60] non-varargs call of varargs method with inexact argument type for last parameter;
08:24:17    cast to java.lang.Object for a varargs call
08:24:17    cast to java.lang.Object[] for a non-varargs call and to suppress this warning
Maybe still of interest to analyse:
> 08:24:17  [INFO] /home/jenkins/agent/workspace/TestResultReporter-plugin_master/src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestAction.java: Some input files use or override a deprecated API.
> 08:24:17  [INFO] /home/jenkins/agent/workspace/TestResultReporter-plugin_master/src/main/java/org/jenkinsci/plugins/JiraTes …

fix #143 java compiler warning

---

src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestAction.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraUtils.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JobConfigMapping.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/TestToIssueMapping.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/api/TestToIssueMappingApi.java

- issue #176
fixed deprecation warnings for findings:
- getInstance() in jenkins.model.Jenkins has been deprecated
- getActiveInstance() in jenkins.model.Jenkins has been deprecated

replace deprecated getInstance and getActiveInstance calls 

---

README.md
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JobConfigMapping.java
src/main/resources/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher/config.jelly
src/main/resources/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher/help-overrideResolvedIssues.html

fix #193
- add missing parts for feature overrideResolvedIssues from PR #80
- try to keep the GUI order of the options also in source code, therefore moved OverrideResolvedIssues after AdditionalAttachments

enable overrideResolvedIssues 

---

src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JobConfigMapping.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/TestToIssueMapping.java

fix #190 
- added nullpointer checks
- consolidation of usage `@NonNull` vs. `@Nonnull`

avoid some NPE on generateSnippet

---

pom.xml
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestAction.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/api/TestToIssueMappingApi.java

Migrate from deprecated EE 8 methods to non-deprecated EE 9 equivalents.
`mvn clean verify`

Migrate from EE 8 to EE 9

---

src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestAction.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraUtils.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JobConfigMapping.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/MetadataCache.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/TestToIssueMapping.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/api/TestToIssueMappingApi.java

[avoid NPE warning in unused code by VS Code Java](https://github.com/jenkinsci/JiraTestResultReporter-plugin/pull/212/commits/414b548c52609112f396fe0d8d51cb280744b801)
[- fix VS Code java warning about Job is a raw type. References to generic type Job<E> should be parameterized](https://github.com/jenkinsci/JiraTestResultReporter-plugin/pull/212/commits/b216588a9ac036a7833f325c535c96a935614da5)
[b216588](https://github.com/jenkinsci/JiraTestResultReporter-plugin/pull/212/commits/b216588a9ac036a7833f325c535c96a935614da5)
- typo

Avoid raw type warnings

---

pom.xml
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
src/main/resources/org/jenkinsci/plugins/JiraTestResultReporter/config/StringArrayFields/help-value.html
src/main/resources/org/jenkinsci/plugins/JiraTestResultReporter/config/StringFields/help-value.html

- json returned from validateFieldConfigs changed,  added an adaptation to support as fallback also JSONArray as type for publisher 
- fixed typo bellow -> below
- fix build issue by going back to previous versions
```
21:28:39  [ERROR] Failed to execute goal on project JiraTestResultReporter: Could not collect dependencies for project org.jenkins-ci.plugins:JiraTestResultReporter:hpi:269.v2994cd1ed4e6
21:28:39  [ERROR] Failed to read artifact descriptor for com.atlassian.jira:jira-rest-java-client-api:jar:6.0.1
21:28:39  [ERROR] 	Caused by: The following artifacts could not be resolved: com.atlassian.jira:jira-rest-java-client-api:pom:6.0.1 (absent): Could not transfer artifact com.atlassian.jira:jira-rest-java-client-api:pom:6.0.1 from/to aws-eks-internal …
```

validateFieldConfigs json changed

---

README.md
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraUtils.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JobConfigMapping.java
src/main/resources/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher/config.jelly
src/main/resources/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher/help-manualAddIssue.html

JENKINS-69312 
- fix for https://issues.jenkins.io/browse/JENKINS-69312
- fix dup https://issues.jenkins.io/browse/JENKINS-67777
with an additional checkbox to enable manual linking

JENKINS-69312 JiraTestResultReporter plugin does not show plus button to create an issue

---

README.md
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/MetadataCache.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/config/SelectableArrayFields.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/config/SelectableFields.java

- Better error logs for #218 
- avoid NPE warning from VS code

Better Log for Issue #218

---

Jenkinsfile
pom.xml
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraUtils.java

- Updates /search API usage due to deprecation announced on https://developer.atlassian.com/changelog/#CHANGE-2046, main  important changes:
- Response will no longer contain the fields: `expand`, `startAt`, `maxResults`, `total`
- Response got new fields: `nextPageToken` and `isLast`
- Mainly we skip the use of the deprecated `startAt` parameter on the REST API request for the search operation and remove the use of `total` on the search result.
- Before this PR:
```
RestClientException{statusCode=Optional.of(410), errorCollections=[ErrorCollection{status=410, errors={}, errorMessages=[The requested API has been removed. Please migrate to the /rest/api/3/search/jql API. A full migration guideline is available at https://developer.atlassian.com/changelog/#CHANGE-2046]}]}
at …
```

Update /search API usage due to deprecation

---

src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraUtils.java

- Recent changes on the search API made the JQL being able to deal now with special char `-` 
- Tested with a simple Java main method
```java
public static void main(String[] args) throws URISyntaxException {
AsynchronousJiraRestClientFactory factory = new AsynchronousJiraRestClientFactory();
JiraRestClient restClient = factory.createWithBasicHttpAuthentication(new URI("my-url"), "my-user", "my-pwd");
String jql = String.format(
"resolution = \"unresolved\" and project = \"%s\" and text ~ \"%s\"",
"BEE", escapeJQL("Test failure - foo-bar/integration.bats.foo-bar rolling upgrade"));
Set<String> fields = new HashSet<>();
fields.add("issueKey");
fields.add("summary");
fields.add("issuetype");
fields.add("created");
fields.add("updated");
fields.add("project");
fields.add("status"); …
```

Bugfix on duplicated issues search operation
