pom.xml
src/main/java/JiraTestResultReporter/JiraReporter.java

Fix for Jenkins 1.577+.
Just increase the version of jenkins up and add a dependency of the junit plugin.

fix for Jenkins 1.577+.

---

src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestAction.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraUtils.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JobConfigMapping.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/config/Entry.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/config/SelectableArrayFields.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/config/SelectableFields.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/config/StringArrayFields.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/config/StringFields.java

Fixes [JENKINS-51243](https://issues.jenkins-ci.org/browse/JENKINS-51243).

Use JiraTestReporter plugin in Jenkins pipeline(Groovy) type of job

---

.gitignore
pom.xml

fix dependency issue with com.google.guava MoreObjects

---

src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/VariableExpander.java
src/main/resources/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher/help-description.html
src/main/resources/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher/help-summary.html
src/main/resources/org/jenkinsci/plugins/JiraTestResultReporter/config/StringArrayFields/help-value.html
src/main/resources/org/jenkinsci/plugins/JiraTestResultReporter/config/StringFields/help-value.html

Introduces a new variable `TEST_PACKAGE_CLASS_METHOD_NAME` which provides the name of the case result test based on its _classname_ (including package) and test method

New variable TEST_PACKAGE_CLASS_METHOD_NAME

---

src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraUtils.java

- See [JENKINS-66092](https://issues.jenkins.io/browse/JENKINS-66092)
- Provides support to upload attachment on newly created issues
- Tested locally:

[JENKINS-66092] Upload attachments on newly created issues

---

src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java

- When Jira server gets temporary down or we experience networking issues the publisher finishes the entire pipeline where it is used as follows:
```
[Pipeline] End of Pipeline
java.lang.NoSuchMethodError: 'void com.google.common.base.Throwables.throwIfUnchecked(java.lang.Throwable)'
at com.atlassian.httpclient.apache.httpcomponents.ApacheAsyncHttpClient.lambda$doExecute$4(ApacheAsyncHttpClient.java:344)
Caused: com.atlassian.httpclient.api.ResponseTransformationException
at com.atlassian.httpclient.api.DefaultResponseTransformation$DefaultResponseTransformationBuilder.lambda$defaultThrowableHandler$1(DefaultResponseTransformation.java:202)
at io.atlassian.util.concurrent.Promises.lambda$biFunction$7(Promises.java:424)
at java.base/java.util.concurrent.CompletableFuture.uniHandle(Completab …
```

Deal with interrumpted network connections with the Jira server

---

src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraUtils.java

- Before this PR if we detect a failed test from a parameterized test, plugin was not able to autoraise an issue providing the following stack trace:
```
RestClientException{statusCode=Optional.of(400), errorCollections=[ErrorCollection{status=400, errors={}, errorMessages=[The text query 'test.ParameterizedTest.test[1\\]' for field 'text' is not valid: probably your range query is incorrect.]}]}
at com.atlassian.jira.rest.client.internal.async.DelegatingPromise.claim(DelegatingPromise.java:45)
at org.jenkinsci.plugins.JiraTestResultReporter.JiraUtils.findIssues(JiraUtils.java:198)
at org.jenkinsci.plugins.JiraTestResultReporter.JiraUtils.createIssue(JiraUtils.java:122)
at org.jenkinsci.plugins.JiraTestResultReporter.JiraTestDataPublisher.raiseIssues(JiraTestDataPublisher.java:269)
at …
```

Fix on creating Jira issues for parameterized tests

---

pom.xml
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestAction.java

Should fix the reported issue by depending on a recent Jenkins core with a recent version of Guava and dropping the Guava JAR previously bundled inside this plugin.

[JENKINS-66949] JiraTestResultReporter:ERROR Unknown: java.lang.NoSuchMethodError: com.google.common.base.Throwables.throwIfUnchecked

---

src/main/resources/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestAction/badge.jelly
src/main/resources/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestAction/helpIssueKeyInput.jelly
src/main/resources/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher/config.jelly
src/main/resources/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher/helpValidateConfigButton.jelly

Preparation for core removing sunset icons: `https://github.com/jenkinsci/jenkins/pull/5778`
@imonteroperez Would be nice if you can also trigger a release after merging this PR.
Thanks in advance!

Prepare for icon removal from core

---

Jenkinsfile

update java version to allow the plugin can be compiled

---

pom.xml
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JobConfigMapping.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/MetadataCache.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/TestToIssueMapping.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/api/TestToIssueMappingApi.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/config/SelectableArrayFields.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/config/SelectableFields.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/config/StringArrayFields.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/config/StringFields.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/config/UserFields.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/restclientextensions/FullStatus.java

Refresh plugin for September 2024

---

README.md
pom.xml
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestData.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/TestToIssueMapping.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/config/Entry.java

- fixed issue #157 on ClassNotFoundException com.atlassian.httpclientapache.httpcomponents.DefaultHttpClientFactory
- corrected some typos in README.md
- removed unneeded imports
Fixes #157

Bugfix for issue 157

---

pom.xml

See https://github.com/jenkinsci/bom/issues/3606#issuecomment-2380118921.

Lower baseline to 2.452.3

---

.github/CODEOWNERS
.gitignore
Jenkinsfile
pom.xml

And other minor build improvements

Test on Java 21

---

pom.xml

- enable update to 3654.v237e4a_f2d8da_ as seen in PR #175 needs jenkins.version 2.452.4
- added variable jenkins.baseline to easy maintenances of jenkins version and corresponding bom artifactid
- added hint on website about current jenkins versions
See failure from https://github.com/jenkinsci/JiraTestResultReporter-plugin/pull/175/checks?check_run_id=32817444468
> [2024-11-11T16:33:16.800Z] Caused by: org.apache.maven.plugin.MojoExecutionException: Dependency io.jenkins.plugins:joda-time-api:jar:2.13.0-93.v9934da_29b_a_e9 requires Jenkins 2.452.4 or higher.

enable update to 3654.v237e4a_f2d8da_

---

src/main/resources/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestAction/badge.jelly
src/main/resources/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestAction/helpIssueKeyInput.jelly
src/main/resources/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestAction/resource.js

https://issues.jenkins.io/browse/JENKINS-74232
https://issues.jenkins.io/browse/JENKINS-74235
I also recommend the diff is looked at with whitespace ignored. I've changed the indentation and github feels lost with the diff unless whitespace is ignored.
[Before the change](https://www.youtube.com/watch?v=JG5yHxUNZjY)
[After the change](https://www.youtube.com/watch?v=9v3u32JsRD0)
~~There's a weird bug with recursive rendering of the Jenkins page when I click on the plus near the failed test. JavaScript that handles the click on that plus comes from JUnit plugin, might be a bug there. To be clear, it also happens before the fix, I just haven't discovered it yet while recording the "Before" video.
I'll investigate this a bit, currently I suspect that it may be cause by `location.reload();` …

[JENKINS-74232][JENKINS-74235] Extract inline JavaScript

---

README.md

fix #189 
- adapted header for consistency
- added code markdown for command line calls
- added description for images

Updated docu

---

pom.xml
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java

- update to jira-rest-client version 5.2.8-platform7-12284590
- update baseline version to .3
- fix typo
- add code comment

jira-rest-client version 5.2.8-platform7-12284590

---

src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java

fix #198 
try to fix some issues with generateSnippets for pipeline configs to get at least some partial output from snippet generator

snippet generator improvement

---

pom.xml
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraUtils.java

Fixes https://github.com/jenkinsci/JiraTestResultReporter-plugin/issues/225

Fix junit-attachments incompatibility

---

src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/MetadataCache.java

retrieve infos for issue #218 
see https://javadoc.io/doc/com.atlassian.jira/jira-rest-java-client-api/latest/com/atlassian/jira/rest/client/api/domain/ServerInfo.html

#218 add further traces to show jira server version info in traces

---

src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraUtils.java

- Follow up from https://github.com/jenkinsci/JiraTestResultReporter-plugin/pull/263

Follow up on bugfix on duplicate detection

---

src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraUtils.java

Fix spotless

---

src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraUtils.java

- Follow up from https://github.com/jenkinsci/JiraTestResultReporter-plugin/pull/264
- On the previous PR we did a quick and dirty fix to make the JQL search API to work on weird scenarios where sometimes the `-` gets escaped and sometimes not (on the Jira API backend)
- We fixed by using `*` as a placeholder but it opens other undesired matches like ` foo - bar` matching with `foo * bar` that could also match with `foo whatever bar` 
- So in this PR we use the escaped double quotes to surround the text inside the JQL statement to ensure the query will match
- Tested locally 
- The following query, returns now values
```
text ~ "\"PCT test failure - io.jenkins.plugins.whatever.TestClass.testMethod(Boolean, Boolean, Boolean, JenkinsMcpClientBuilder, JenkinsRule)\""
```
- The following …

Use double quotes for JQL
